- name: CREATE POOL & POOL MEMBERS 
  hosts: bigips 
  connection: local
  gather_facts: false
  vars:
   ansible_python_interpreter: /usr/bin/python3
   gather_facts: false
   provider:
     password: "{{pass}}"
     server: "{{server}}"
     user: "{{user}}"
     validate_certs: no
     server_port: 443

  vars_files:
    - variable_file.yaml

  tasks:

  - name: CREATING POOL
    bigip_pool:
        provider: "{{ provider}}"
        state: "present"
        name: "{{tenant_name}}_http-pool"
        lb_method: "round-robin"
        # delegate_to: localhost

  - name: ADDING POOL MEMBERS
    bigip_pool_member:
        provider: "{{ provider}}"    
        pool: "{{tenant_name}}_http-pool"
        host: "{{item.host}}"
        port: "{{item.port}}"
    with_items: "{{pool_members}}"
    delegate_to: localhost
